# base64 skull only
catcher-item:
  texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjBkYTIzY2M5Y2I3OTI4MTQwNTg0NDQxYzM3NDBmOGY0MTEzNWEyNDc1Y2MzNGJhMDVjMGEyMzNhYWRmNjNmYiJ9fX0='
  name: '&bCatcher'
  lore:
    - '&8Right click catch a selected entity to egg.'

# second
select-duration: 5

# *block
laser-distance: 10

# *tick
laser-duration: 100